name: Weekly Tests

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  tests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-med
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Rust Corset
        uses: ./.github/actions/setup-rust-corset

      - name: Run Weekly tests
        run: ./gradlew weeklyTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: fields,expand,expand,expand
          WEEKLY_TESTS_PARALLELISM: 4

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: nightly-tests-report
          path: build/reports/tests/**/*

  go-corset-tests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-med
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Go Corset
        uses: ./.github/actions/setup-go-corset

      - name: Run Weekly tests
        run: GOMEMLIMIT=196GiB ./gradlew weeklyTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: disable
          GOCORSET_FLAGS: -wd --ansi-escapes=false --report --air

      - name: Failure Notification
        if: ${{ failure() || cancelled() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
             name: "Weekly"
             status: "${{ job.status }}"
