name: reference tests

on:
  schedule:
    - cron: "0 23 * * 1-5"
  workflow_dispatch:

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  ethereum-tests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Rust Corset
        uses: ./.github/actions/setup-rust-corset

      - name: Generate zkevm_for_reference_tests.bin
        run: cd ./linea-constraints; make zkevm_for_reference_tests.bin -B; cd ..

      - name: Generate General State Reference Tests
        run:  ./gradlew generateGeneralStateReferenceTests -Dorg.gradle.parallel=true -Dorg.gradle.caching=true
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: fields,expand,expand,expand

      - name: Run General State Reference Tests
        run: ./gradlew referenceGeneralStateTests
        env:
          REFERENCE_TESTS_PARALLELISM: 10
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: fields,expand,expand,expand

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ethereum-tests-report
          path: |
            reference-tests/build/reports/tests/**/*
            tmp/local/*

      - name: Failure Notification
        if: ${{ failure() || cancelled() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
             name: "Daily Reference Tests (Rust Corset)"
             status: "${{ job.status }}"

  ethereum-tests-go-corset:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Go Corset
        uses: ./.github/actions/setup-go-corset

      - name: Generate zkevm_for_reference_tests.bin
        run: cd ./linea-constraints; make zkevm_for_reference_tests.bin -B; cd ..

      - name: Generate General State Reference Tests
        run: ./gradlew generateGeneralStateReferenceTests -Dorg.gradle.caching=true
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: fields,expand,expand,expand

      - name: Run General State Reference Tests
        run: GOMEMLIMIT=196GiB ./gradlew referenceGeneralStateTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: disable
          GOCORSET_FLAGS: -wd --ansi-escapes=false --report --air

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ethereum-tests-go-corset-report
          path: |
            reference-tests/build/reports/tests/**/*
            tmp/local/*

      - name: Failure Notification
        if: ${{ failure() || cancelled() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
             name: "Daily Reference Tests (Go Corset)"
             status: "${{ job.status }}"
